// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ohewklfngLzfIdVybnH6efPhgFUUqdk',
    appId: '1:456576840158:web:712d27cf2d6e983928ed4f',
    messagingSenderId: '456576840158',
    projectId: 'discovery-moebel-app',
    authDomain: 'discovery-moebel-app.firebaseapp.com',
    storageBucket: 'discovery-moebel-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKjMVHX1fXi4Th8j03VMo9s1I8uA-5_HY',
    appId: '1:456576840158:android:2e78ec838dae231628ed4f',
    messagingSenderId: '456576840158',
    projectId: 'discovery-moebel-app',
    storageBucket: 'discovery-moebel-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeJrEGCngO_b-idwrpawHFtp9MuIMAZbg',
    appId: '1:456576840158:ios:7466d72fdfb80cb128ed4f',
    messagingSenderId: '456576840158',
    projectId: 'discovery-moebel-app',
    storageBucket: 'discovery-moebel-app.appspot.com',
    iosBundleId: 'com.maxwarbeck.flutterQrcodeScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeJrEGCngO_b-idwrpawHFtp9MuIMAZbg',
    appId: '1:456576840158:ios:4b091c2f62dfea6928ed4f',
    messagingSenderId: '456576840158',
    projectId: 'discovery-moebel-app',
    storageBucket: 'discovery-moebel-app.appspot.com',
    iosBundleId: 'com.example.flutterQrcodeScanner.RunnerTests',
  );
}
